version: '3'

services:
  chat-webapp-mdb-s1:
    image: 'chat-webapp-pdb-s1:SNAPSHOT'
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      JVM_OPTS: "-Xmx128m -Xms128m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      APP_OPTS: "--spring.datasource.url=jdbc:postgresql://storage-postgres:5432/chat"

  storage-postgres:
    image: 'postgres:10'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
